# Copyright (c) 2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  version: 0.8

  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: v0.7.1
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-ncs.yml
        path-prefix: deps
        name-allowlist:
          - nrf
          - zephyr
          - cmsis
          - hal_nordic
          - mbedtls
          - mbedtls-nrf
          - mcuboot
          - net-tools
          - nrfxlib
          - qcbor
          - segger
          - tfm-mcuboot
          - tinycrypt
          - trusted-firmware-m
          - zcbor

    - name: golioth-zephyr-boards
      path: deps/modules/lib/golioth-boards
      revision: v1.0.0
      url: git@github.com:golioth/golioth-zephyr-boards.git

    - name: libostentus
      path: deps/modules/lib/libostentus
      revision: v1.0.0
      url: git@github.com:golioth/libostentus.git

    - name: zephyr-network-info
      path: deps/modules/lib/network-info
      revision: v1.0.1
      url: https://github.com/golioth/zephyr-network-info

    - name: minmea
      path: app/src/lib/minmea
      revision: 85439b97dd4984c5efb84ce954b85088e781dae8
      url: https://github.com/kosma/minmea.git

  self:
    path: app
